repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: trailing-whitespace
    exclude: ".*.md"
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-yaml
  - id: debug-statements
  - id: name-tests-test
    args: ['--django']
  - id: requirements-txt-fixer
  - id: flake8
    args: ['--max-line-length', '120']
    exclude: "tests/.*"
  - id: check-added-large-files
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.4.0
  hooks:
  - id: reorder-python-imports
    language_version: python3
- repo: https://github.com/asottile/add-trailing-comma
  rev: v0.8.0
  hooks:
  - id: add-trailing-comma
